[job]
exp_name = "cogvideo-mlp-3s-4090"

[model]
name = "cogvideo"
size = "5B"
ssm_layer = "ttt_mlp"
ttt_base_lr = 0.1
mini_batch_size = 16  # 从64降低到16以适应4090显存
video_length = "3sec"

[optimizer]
name = "AdamW"
lr = 1e-5
lr_ssm = 1e-4
lr_end = 1e-5
lr_schedule = "linear"
lr_ssm_schedule = "cosine"
gradient_clipping_norm = 0.1

[training]
global_batch_size = 16  # 从64降低到16以适应4090显存
grad_accum_steps = 4    # 增加梯度累积步数以保持有效批量大小
warmup_steps = 100
steps = 5000
adapter_method = "sft"
dataset_path = TODO
jsonl_paths = TODO

[remat]
transformer_checkpoint_layer_group_size = 1
scan_checkpoint_group_size = 8  # 从16减少到8，增加检查点频率

[parallelism]
fsdp_unsharded_dtype = 'bfloat16'
dp_replicate = 1       # 减少复制
dp_sharding = 4        # 增加分片以减少每个GPU的内存使用
tp_sharding = 1        # 对于3秒视频可以不使用张量并行

[checkpoint]
interval = 100         # 从500减少到100，增加检查点保存频率
init_state_dir = TODO

[wandb]
project = "cogvideo_release"
entity = "ttt-vid"
log_interval = 1