[job]
exp_name = "cogvideo-mlp-9s-4090"

[model]
name = "cogvideo"
size = "5B"
ssm_layer = "ttt_mlp"
ttt_base_lr = 0.1
mini_batch_size = 8  # 从64降低到8以适应4090显存和更长视频
video_length = "9sec"

[optimizer]
name = "AdamW"
lr = 1e-5
lr_ssm = 1e-4
lr_end = 1e-5
lr_schedule = "linear"
lr_ssm_schedule = "cosine"
gradient_clipping_norm = 0.1

[training]
global_batch_size = 8  # 从64降低到8以适应4090显存
grad_accum_steps = 8    # 增加梯度累积步数以保持有效批量大小
warmup_steps = 100
steps = 5000
adapter_method = "qkvo"  # 对于9秒以上视频，使用qkvo适配器方法
dataset_path = TODO
jsonl_paths = TODO

[remat]
transformer_checkpoint_layer_group_size = 1
scan_checkpoint_group_size = 4  # 从16减少到4，大幅增加检查点频率

[parallelism]
fsdp_unsharded_dtype = 'bfloat16'
dp_replicate = 1       # 减少复制
dp_sharding = 2        # 减少分片以便使用张量并行
tp_sharding = 2        # 启用张量并行以分散内存使用

[checkpoint]
interval = 50          # 从500减少到50，大幅增加检查点保存频率
init_state_dir = TODO  # 应该指向3秒训练的最终检查点

[wandb]
project = "cogvideo_release"
entity = "ttt-vid"
log_interval = 1